controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

mark_message_read:
    path: /message/{id}/read
    controller: App\Controller\ChatController::markMessageAsRead
    methods: [POST]

